version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.http.middlewares.test-auth.basicauth.users=test:admin:$$apr1$$qmtogpy1$$vivO9AP/jTd9MMDEqvk/L."
      traefik.enable: true
      traefik.frontend.rule: "Host:traefik.yourdomain.com"
      # get md5 from htpasswd or http://www.htaccesstools.com/htpasswd-generator/
      # and then double all $ to $$ to avoid docker-compose 
      traefik.frontend.auth.basic: "admin:$$apr1$$qmtogpy1$$vivO9AP/jTd9MMDEqvk/L."
      traefik.port: 8080
    logging:
      options:
        max-size: 5M 
    networks:
        - web
        
networks:
  web:
    external: true
